version: '3.8'

services:
  backend:
    build:
      context: ./fingerprint-auth-demo-backend-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://fingerprint-auth-demo.onrender.com
      - FINGERPRINT_API_KEY=${FINGERPRINT_API_KEY}
      - FINGERPRINT_API_URL=https://api.fpjs.io
      - FINGERPRINT_API_REGION=us
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./fingerprint-auth-demo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_FINGERPRINT_PUBLIC_API_KEY=${VITE_FINGERPRINT_PUBLIC_API_KEY}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data: