version: '3.8'

services:
  backend:
    build:
      context: ./fingerprint-auth-demo-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - FINGERPRINT_SECRET_KEY=${FINGERPRINT_SECRET_KEY}
      - FINGERPRINT_PUBLIC_KEY=${FINGERPRINT_PUBLIC_KEY}
      - FINGERPRINT_API_URL=${FINGERPRINT_API_URL:-https://ap.api.fpjs.io}
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./fingerprint-auth-demo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_FINGERPRINT_PUBLIC_KEY=${FINGERPRINT_PUBLIC_KEY}
      - VITE_FINGERPRINT_PROXY_BASE_URL=${FINGERPRINT_PROXY_BASE_URL:-http://localhost:8080}
      - VITE_FINGERPRINT_USE_PROXY=${FINGERPRINT_USE_PROXY:-false}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data: