services:
  - type: web
    name: fingerprint-auth-demo-backend
    env: docker
    rootDir: fingerprint-auth-demo-backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://fingerprint-auth-demo-frontend.onrender.com
    disk:
      name: maven-cache
      mountPath: /root/.m2/repository
      sizeGB: 1 